"""
Runs self verification on the annotations specified in the config file.

Usage:
    python self_verification.py data=your_dataset_name
"""

import ast
import os

import CONSTANTS as const
import hydra
import pandas as pd
from hydra import compose, initialize
from hydra.core.hydra_config import HydraConfig
from omegaconf import DictConfig, OmegaConf
from tqdm import tqdm
from transformers import AutoTokenizer
from utils.evaluation import post_process_extractions
from utils.llm import call_llm, unload_llm
from utils.prompters import get_sv_prompt
from vllm import LLM


def self_verification(
    cfg: DictConfig, annotations: pd.DataFrame, sv_annotation_file_path: str
) -> str:
    """Runs self-verification on the annotations generated by the in-context NED model, and saves the results in a new csv file.

    Args:
        cfg (DictConfig): The configuration object.
        annotation_file_path (str): The path to the csv file containing the annotations.

    Returns:
        str: The path to the csv file containing the self-verification results.
    """

    for column in ["gt entities", "pred entities"]:
        annotations[column] = annotations[column].apply(ast.literal_eval)

    gts = annotations["gt entities"].tolist()
    texts = annotations["text"].tolist()

    if "gpt" not in cfg.model:
        tokenizer = AutoTokenizer.from_pretrained(
            const.MODEL_NAME2HUGGINGFACE[cfg.model],
            token=os.getenv("HF_API_TOKEN"),
            revision=cfg.model_revision_hash,
        )
        langauge_model = LLM(
            model=const.MODEL_NAME2HUGGINGFACE[cfg.model],
            trust_remote_code=True,
            seed=cfg.seed,
            dtype="half",
            revision=cfg.model_revision_hash,
            tokenizer_revision=cfg.model_revision_hash,
        )
    else:
        tokenizer = None
        langauge_model = None

    sampleid2num_entities = {}
    sample2annotation_unique = {}
    for index in tqdm(range(0, len(texts), cfg.batch_size)):
        batch_gt = gts[index : index + cfg.batch_size]
        batch_text = texts[index : index + cfg.batch_size]
        batch_annotations = (
            annotations["pred entities"].iloc[index : index + cfg.batch_size].tolist()
        )

        batch_messages = []
        for sample_id, (sample_annotation, sample_text) in enumerate(
            zip(batch_annotations, batch_text)
        ):
            sample_annotation_unique = [
                e for e in list(dict.fromkeys(sample_annotation)) if e != ""
            ]
            sampleid2num_entities[sample_id] = len(sample_annotation_unique)
            sample2annotation_unique[sample_id] = sample_annotation_unique
            sample_messages = [
                get_sv_prompt(
                    entity=entity,
                    entity_type=const.DATA_ENTITY_DICT[cfg.data.dataset],
                    context=sample_text,
                )
                for entity in sample_annotation_unique
            ]
            batch_messages.extend(sample_messages)

        batch_output, _ = call_llm(langauge_model, tokenizer, batch_messages, cfg)

        # unravel the LLM outputs per sample
        current_index = 0
        batch_annotations_sv = []
        batch_prompt = []
        batch_sv_output = []
        for sample_index, sample_annotation in enumerate(batch_annotations):
            sample_start_index = current_index
            sample_end_index = current_index + sampleid2num_entities[sample_index]
            current_index = sample_end_index
            sample_sv_output = batch_output[sample_start_index:sample_end_index]
            sample_annotation_unique = sample2annotation_unique[sample_index]
            sample_annotation_sv = []
            for entity_index, sv_output in enumerate(sample_sv_output):
                for line in sv_output.split("\n"):
                    line = line.replace("*", "")
                    if "yes" in line.lower():
                        sample_annotation_sv.append(
                            sample_annotation_unique[entity_index]
                        )
                        break

            batch_annotations_sv.append(sample_annotation_sv)
            batch_prompt.append(batch_messages[sample_start_index:sample_end_index])
            batch_sv_output.append("\n".join(sample_sv_output).replace("\n", " & "))

        processed_batch_annotations_sv = [
            post_process_extractions(
                entities,
                batch_text[idx],
                treat_special_tokens="bc" in cfg.data.dataset,
                resolve_overlapping_entities=False,
            )
            for idx, entities in enumerate(batch_annotations_sv)
        ]

        batch_results = pd.DataFrame(
            {
                "id": annotations["id"].iloc[index : index + cfg.batch_size],
                "text": batch_text,
                "prompt": batch_prompt,
                "model output": batch_sv_output,
                "gt entities": batch_gt,
                "pred entities": processed_batch_annotations_sv,
            }
        )

        batch_results.to_csv(
            sv_annotation_file_path,
            mode="a",
            header=not os.path.exists(sv_annotation_file_path),
            index=False,
        )

    unload_llm(langauge_model)
    return sv_annotation_file_path


@hydra.main(
    config_path="configs/picle_self_ver", config_name="config", version_base=None
)
def main(cfg: DictConfig):

    # Check if the output directory exists, if not create it
    output_dir = HydraConfig.get().runtime.output_dir
    os.makedirs(output_dir, exist_ok=True)

    # Run self-verification on the annotations
    if cfg.get("annotation_file_path"):
        sv_annotation_file_path = cfg.get("annotation_file_path").replace(
            ".csv", "_sv.csv"
        )
        annotations = pd.read_csv(cfg.get("annotation_file_path"))
    elif cfg.get("clusters"):
        sv_annotation_file_path = os.path.join(output_dir, "sv_results.csv")
        # find the annotation file path for all clusters
        results_folder = "outputs"
        sorted_experiments_desc = sorted(os.listdir(results_folder), reverse=True)
        cluster_id2annotation_file_path = {}
        for day in sorted_experiments_desc:
            for time in sorted(
                os.listdir(os.path.join(results_folder, day)), reverse=True
            ):
                with initialize(
                    config_path=os.path.join(results_folder, day, time, ".hydra")
                ):
                    exp_cfg = compose(config_name="config")

                exp_cfg_dict = OmegaConf.to_container(exp_cfg, resolve=True)
                dataset = exp_cfg_dict["data"]["dataset"]
                cluster_id = exp_cfg_dict["cluster_id"]
                if dataset == cfg.data.dataset and cluster_id in cfg.get("clusters"):
                    annotation_file_path = os.path.join(
                        results_folder, day, time, "outputs", "results.csv"
                    )
                    cluster_id2annotation_file_path[cluster_id] = annotation_file_path

        data_complete = True
        for cluster_id in cfg.get("clusters"):
            if cluster_id not in cluster_id2annotation_file_path:
                print(
                    f"Results for cluster {cluster_id} does not exist. Please run in-context NED for this cluster first."
                )
                data_complete = False
        if not data_complete:
            exit(1)

        # concatenate all the annotations
        annotations = pd.EmptyDataFrame()
        for cluster_id, annotation_file_path in cluster_id2annotation_file_path.items():
            cluster_annotations = pd.read_csv(annotation_file_path)
            cluster_annotations["cluster_id"] = cluster_id
            annotations = pd.concat(
                [annotations, cluster_annotations], ignore_index=True
            )

        # group by text and merge the pred entities in a list
        annotations = (
            annotations["text", "pred entities", "gt entities"]
            .groupby("text")
            .agg(
                {
                    "pred entities": lambda x: list(set(x)),
                    "gt entities": lambda x: list(set(x)),
                }
            )
            .reset_index()
        )

    self_verification(cfg, annotations, sv_annotation_file_path)


if __name__ == "__main__":
    main()
